TZ: Asia/Shanghai
FRUIT_BEAN_CARD: true
JDJOY_APPLYJDBEAN: 2000
JDJOY_HELPSELF: true
JD_BEAN_SIGN_NOTIFY_SIMPLE: true
JD_COOKIE: pt_key=AAJhTC1VADCLOxMudYJ8sLvpeOSGrtCFliL2cKdxpUwrIzRgx2s0NesQTZisQU77hBsB0YNGjtk; pt_pin=jd_6b55e5fcda417;
JOIN_PK_TEAM: true
JOY_FEED_COUNT: 20
JOY_RUN_HELP_MYSELF: true
JOY_TEAM_LEVEL: 2&10&50
MARKET_COIN_TO_BEANS: 20
PAT: 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
PUSH_KEY: SCT79236TTP5zRKzaTgDueeSk8mWU1SPI
SUPERMARKET_LOTTERY: true
FS_LEVEL: car
