# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_joy（手动）

on:
  workflow_dispatch:
#  schedule:
#    - cron: '35 9 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_joy
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install png-js
          npm install canvas
          
      - name: '运行 【宠汪汪二代目】'
        run: |
          node jd_joy.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}